// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseRequestProto.proto

#ifndef PROTOBUF_INCLUDED_BaseRequestProto_2eproto
#define PROTOBUF_INCLUDED_BaseRequestProto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BaseRequestProto_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_BaseRequestProto_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_BaseRequestProto_2eproto();
namespace protocol {
class CIMRequest;
class CIMRequestDefaultTypeInternal;
extern CIMRequestDefaultTypeInternal _CIMRequest_default_instance_;
}  // namespace protocol
namespace google {
namespace protobuf {
template<> ::protocol::CIMRequest* Arena::CreateMaybeMessage<::protocol::CIMRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protocol {

// ===================================================================

class CIMRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.CIMRequest) */ {
 public:
  CIMRequest();
  virtual ~CIMRequest();

  CIMRequest(const CIMRequest& from);

  inline CIMRequest& operator=(const CIMRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CIMRequest(CIMRequest&& from) noexcept
    : CIMRequest() {
    *this = ::std::move(from);
  }

  inline CIMRequest& operator=(CIMRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CIMRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CIMRequest* internal_default_instance() {
    return reinterpret_cast<const CIMRequest*>(
               &_CIMRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CIMRequest* other);
  friend void swap(CIMRequest& a, CIMRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CIMRequest* New() const final {
    return CreateMaybeMessage<CIMRequest>(nullptr);
  }

  CIMRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CIMRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CIMRequest& from);
  void MergeFrom(const CIMRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CIMRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string reqMsg = 1;
  bool has_reqmsg() const;
  void clear_reqmsg();
  static const int kReqMsgFieldNumber = 1;
  const ::std::string& reqmsg() const;
  void set_reqmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_reqmsg(::std::string&& value);
  #endif
  void set_reqmsg(const char* value);
  void set_reqmsg(const char* value, size_t size);
  ::std::string* mutable_reqmsg();
  ::std::string* release_reqmsg();
  void set_allocated_reqmsg(::std::string* reqmsg);

  // required int64 requestId = 2;
  bool has_requestid() const;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int64 requestid() const;
  void set_requestid(::google::protobuf::int64 value);

  // required int32 type = 3;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protocol.CIMRequest)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr reqmsg_;
  ::google::protobuf::int64 requestid_;
  ::google::protobuf::int32 type_;
  friend struct ::TableStruct_BaseRequestProto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CIMRequest

// required int64 requestId = 2;
inline bool CIMRequest::has_requestid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CIMRequest::clear_requestid() {
  requestid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 CIMRequest::requestid() const {
  // @@protoc_insertion_point(field_get:protocol.CIMRequest.requestId)
  return requestid_;
}
inline void CIMRequest::set_requestid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  requestid_ = value;
  // @@protoc_insertion_point(field_set:protocol.CIMRequest.requestId)
}

// required string reqMsg = 1;
inline bool CIMRequest::has_reqmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CIMRequest::clear_reqmsg() {
  reqmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& CIMRequest::reqmsg() const {
  // @@protoc_insertion_point(field_get:protocol.CIMRequest.reqMsg)
  return reqmsg_.GetNoArena();
}
inline void CIMRequest::set_reqmsg(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  reqmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.CIMRequest.reqMsg)
}
#if LANG_CXX11
inline void CIMRequest::set_reqmsg(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  reqmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.CIMRequest.reqMsg)
}
#endif
inline void CIMRequest::set_reqmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  reqmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.CIMRequest.reqMsg)
}
inline void CIMRequest::set_reqmsg(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  reqmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.CIMRequest.reqMsg)
}
inline ::std::string* CIMRequest::mutable_reqmsg() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:protocol.CIMRequest.reqMsg)
  return reqmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CIMRequest::release_reqmsg() {
  // @@protoc_insertion_point(field_release:protocol.CIMRequest.reqMsg)
  if (!has_reqmsg()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return reqmsg_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CIMRequest::set_allocated_reqmsg(::std::string* reqmsg) {
  if (reqmsg != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  reqmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reqmsg);
  // @@protoc_insertion_point(field_set_allocated:protocol.CIMRequest.reqMsg)
}

// required int32 type = 3;
inline bool CIMRequest::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CIMRequest::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 CIMRequest::type() const {
  // @@protoc_insertion_point(field_get:protocol.CIMRequest.type)
  return type_;
}
inline void CIMRequest::set_type(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  type_ = value;
  // @@protoc_insertion_point(field_set:protocol.CIMRequest.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_BaseRequestProto_2eproto
