// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseRequestProto.proto

#include "protocol/BaseRequestProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace protocol {
class CIMRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CIMRequest> _instance;
} _CIMRequest_default_instance_;
}  // namespace protocol
static void InitDefaultsCIMRequest_BaseRequestProto_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_CIMRequest_default_instance_;
    new (ptr) ::protocol::CIMRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::CIMRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CIMRequest_BaseRequestProto_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCIMRequest_BaseRequestProto_2eproto}, {}};

void InitDefaults_BaseRequestProto_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_CIMRequest_BaseRequestProto_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_BaseRequestProto_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_BaseRequestProto_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_BaseRequestProto_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_BaseRequestProto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protocol::CIMRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protocol::CIMRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protocol::CIMRequest, requestid_),
  PROTOBUF_FIELD_OFFSET(::protocol::CIMRequest, reqmsg_),
  PROTOBUF_FIELD_OFFSET(::protocol::CIMRequest, type_),
  1,
  0,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::protocol::CIMRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_CIMRequest_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_BaseRequestProto_2eproto = {
  {}, AddDescriptors_BaseRequestProto_2eproto, "BaseRequestProto.proto", schemas,
  file_default_instances, TableStruct_BaseRequestProto_2eproto::offsets,
  file_level_metadata_BaseRequestProto_2eproto, 1, file_level_enum_descriptors_BaseRequestProto_2eproto, file_level_service_descriptors_BaseRequestProto_2eproto,
};

const char descriptor_table_protodef_BaseRequestProto_2eproto[] =
  "\n\026BaseRequestProto.proto\022\010protocol\"=\n\nCI"
  "MRequest\022\021\n\trequestId\030\002 \002(\003\022\016\n\006reqMsg\030\001 "
  "\002(\t\022\014\n\004type\030\003 \002(\005"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_BaseRequestProto_2eproto = {
  false, InitDefaults_BaseRequestProto_2eproto, 
  descriptor_table_protodef_BaseRequestProto_2eproto,
  "BaseRequestProto.proto", &assign_descriptors_table_BaseRequestProto_2eproto, 97,
};

void AddDescriptors_BaseRequestProto_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_BaseRequestProto_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_BaseRequestProto_2eproto = []() { AddDescriptors_BaseRequestProto_2eproto(); return true; }();
namespace protocol {

// ===================================================================

void CIMRequest::InitAsDefaultInstance() {
}
class CIMRequest::HasBitSetters {
 public:
  static void set_has_requestid(CIMRequest* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_reqmsg(CIMRequest* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_type(CIMRequest* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CIMRequest::kRequestIdFieldNumber;
const int CIMRequest::kReqMsgFieldNumber;
const int CIMRequest::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CIMRequest::CIMRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.CIMRequest)
}
CIMRequest::CIMRequest(const CIMRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reqmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_reqmsg()) {
    reqmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reqmsg_);
  }
  ::memcpy(&requestid_, &from.requestid_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&requestid_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:protocol.CIMRequest)
}

void CIMRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_CIMRequest_BaseRequestProto_2eproto.base);
  reqmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&requestid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&requestid_)) + sizeof(type_));
}

CIMRequest::~CIMRequest() {
  // @@protoc_insertion_point(destructor:protocol.CIMRequest)
  SharedDtor();
}

void CIMRequest::SharedDtor() {
  reqmsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CIMRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CIMRequest& CIMRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CIMRequest_BaseRequestProto_2eproto.base);
  return *internal_default_instance();
}


void CIMRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.CIMRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    reqmsg_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&requestid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&type_) -
        reinterpret_cast<char*>(&requestid_)) + sizeof(type_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CIMRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CIMRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required string reqMsg = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("protocol.CIMRequest.reqMsg");
        object = msg->mutable_reqmsg();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // required int64 requestId = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_requestid(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // required int32 type = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_type(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CIMRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.CIMRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string reqMsg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reqmsg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reqmsg().data(), static_cast<int>(this->reqmsg().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protocol.CIMRequest.reqMsg");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int64 requestId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_requestid(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &requestid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          HasBitSetters::set_has_type(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.CIMRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.CIMRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CIMRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.CIMRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string reqMsg = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reqmsg().data(), static_cast<int>(this->reqmsg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.CIMRequest.reqMsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->reqmsg(), output);
  }

  // required int64 requestId = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->requestid(), output);
  }

  // required int32 type = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.CIMRequest)
}

::google::protobuf::uint8* CIMRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.CIMRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string reqMsg = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reqmsg().data(), static_cast<int>(this->reqmsg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.CIMRequest.reqMsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->reqmsg(), target);
  }

  // required int64 requestId = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->requestid(), target);
  }

  // required int32 type = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.CIMRequest)
  return target;
}

size_t CIMRequest::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:protocol.CIMRequest)
  size_t total_size = 0;

  if (has_reqmsg()) {
    // required string reqMsg = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reqmsg());
  }

  if (has_requestid()) {
    // required int64 requestId = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->requestid());
  }

  if (has_type()) {
    // required int32 type = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  return total_size;
}
size_t CIMRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.CIMRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string reqMsg = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reqmsg());

    // required int64 requestId = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->requestid());

    // required int32 type = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.CIMRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const CIMRequest* source =
      ::google::protobuf::DynamicCastToGenerated<CIMRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.CIMRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.CIMRequest)
    MergeFrom(*source);
  }
}

void CIMRequest::MergeFrom(const CIMRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.CIMRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      reqmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reqmsg_);
    }
    if (cached_has_bits & 0x00000002u) {
      requestid_ = from.requestid_;
    }
    if (cached_has_bits & 0x00000004u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CIMRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.CIMRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CIMRequest::CopyFrom(const CIMRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.CIMRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void CIMRequest::Swap(CIMRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CIMRequest::InternalSwap(CIMRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  reqmsg_.Swap(&other->reqmsg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(requestid_, other->requestid_);
  swap(type_, other->type_);
}

::google::protobuf::Metadata CIMRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BaseRequestProto_2eproto);
  return ::file_level_metadata_BaseRequestProto_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::protocol::CIMRequest* Arena::CreateMaybeMessage< ::protocol::CIMRequest >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::CIMRequest >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
